export const classQuotes = [
  { text: "Pure mathematics is, in its way, the poetry of logical ideas.", author: "Albert Einstein" },
  { text: "The only way to learn mathematics is to do mathematics.", author: "Paul Halmos" },
  { text: "Mathematics is the music of reason.", author: "James Joseph Sylvester" },
  { text: "Nature is written in mathematical language.", author: "Galileo Galilei" },
  { text: "In mathematics, the art of proposing a question must be held of higher value than solving it.", author: "Georg Cantor" },
  { text: "God used beautiful mathematics in creating the world.", author: "Paul Dirac" },
  { text: "Mathematics is the queen of science, and arithmetic the queen of mathematics.", author: "Carl Friedrich Gauss" },
  { text: "Black holes are where God divided by zero.", author: "Steven Wright" },
  { text: "Millions saw the apple fall, but Newton asked why.", author: "Bernard Baruch" },
  { text: "Everything is theoretical until you come up with a proof.", author: "Katherine Johnson" },
  { text: "Look up at the stars and not down at your feet.", author: "Stephen Hawking" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "The seed of every great thing is an idea.", author: "Nikola Tesla" },
  { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
  { text: "For a successful technology, reality must take precedence over public relations, for Nature cannot be fooled.", author: "Richard Feynman" },
  { text: "What I cannot create, I do not understand.", author: "Richard Feynman" },
  { text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "The science of today is the technology of tomorrow.", author: "Edward Teller" },
  { text: "Software is eating the world.", author: "Marc Andreessen" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.", author: "Mark Zuckerberg" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "If you double the number of experiments you do per year you’re going to double your inventiveness.", author: "Jeff Bezos" },
  { text: "I think it is possible for ordinary people to choose to be extraordinary.", author: "Elon Musk" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "Persistence is very important. You should not give up unless you are forced to give up.", author: "Elon Musk" },
  { text: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.", author: "Bill Gates" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
  { text: "Don't compare yourself with anyone in this world... if you do so, you are insulting yourself.", author: "Bill Gates" },
  { text: "Computational thinking will be everywhere and applied by everyone.", author: "Jeannette Wing" },
  { text: "The most dangerous phrase in the language is, 'We've always done it this way.'", author: "Grace Hopper" },
  { text: "It's easier to ask forgiveness than it is to get permission.", author: "Grace Hopper" },
  { text: "The computer was born to solve problems that did not exist before.", author: "Bill Gates" },
  { text: "Programming is the closest thing we have to magic.", author: "Elon Musk" },
  { text: "Computer science is no more about computers than astronomy is about telescopes.", author: "Edsger W. Dijkstra" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "The question of whether machines can think is about as relevant as the question of whether submarines can swim.", author: "Edsger W. Dijkstra" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke" },
  { text: "Hardware is the part of a computer that you can kick.", author: "Jeff Pesis" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "Most good programmers do programming not because they expect to get paid, but because it is fun to program.", author: "Linus Torvalds" },
  { text: "The secret to successful hiring is this: look for the people who want to change the world.", author: "Marc Benioff" },
  { text: "Great things in business are never done by one person.", author: "Steve Jobs" },
  { text: "We are reaching the stage where problems that we must solve are going to become insoluble without computers.", author: "John von Neumann" },
  { text: "If you don't fail at least 90 percent of the time, you're not aiming high enough.", author: "Alan Kay" },
  { text: "Data is the new oil.", author: "Clive Humby" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Optimization is the root of all evil in programming.", author: "Donald Knuth" },
  { text: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", author: "Bill Gates" },
  { text: "The analytical engine weaves algebraic patterns just as the Jacquard loom weaves flowers and leaves.", author: "Ada Lovelace" },
  { text: "Forget about being an expert. Just be a learner.", author: "Satya Nadella" },
  { text: "Our industry does not respect tradition — it only respects innovation.", author: "Satya Nadella" },
  { text: "The advance of technology is based on making it fit in so that you don't really even notice it.", author: "Bill Gates" },
  { text: "The technology you use is not as important as the people you help with it.", author: "Unknown" },
  { text: "Information is the resolution of uncertainty.", author: "Claude Shannon" },
  { text: "One man's constant is another man's variable.", author: "Alan Perlis" },
  { text: "A primary cause of complexity is that software vendors uncritically adopt any feature users suggest.", author: "Niklaus Wirth" },
  { text: "The function of a good software is to make the complex appear simple.", author: "Grady Booch" },
  { text: "The world is one big data problem.", author: "Andrew Ng" },
  { text: "We're not just building a search engine. We're building an AI.", author: "Larry Page" },
  { text: "Always deliver more than expected.", author: "Larry Page" },
  { text: "If you're changing the world, you're working on important things. You're excited to get up in the morning.", author: "Larry Page" },
  { text: "You don't need to have a 100-person company to develop that idea.", author: "Larry Page" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "Technology is best when it brings people together.", author: "Matt Mullenweg" },
  { text: "The intersection of law and technology is going to be very interesting.", author: "Tim Cook" },
  { text: "Let's go invent tomorrow instead of worrying about what happened yesterday.", author: "Steve Jobs" },
  { text: "Science is not only a disciple of reason but also one of romance and passion.", author: "Stephen Hawking" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "In science there is only physics; all the rest is stamp collecting.", author: "Ernest Rutherford" },
  { text: "The universe is under no obligation to make sense to you.", author: "Neil deGrasse Tyson" },
  { text: "Errors using inadequate data are much less than those using no data at all.", author: "Charles Babbage" },
  { text: "The present is theirs; the future, for which I really worked, is mine.", author: "Nikola Tesla" },
  { text: "Science is the great antidote to the poison of enthusiasm and superstition.", author: "Adam Smith" },
  { text: "I am enough of an artist to draw freely upon my imagination.", author: "Albert Einstein" },
  { text: "Life would be tragic if it weren't funny.", author: "Stephen Hawking" },
  { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
  { text: "We are just an advanced breed of monkeys on a minor planet of a very average star.", author: "Stephen Hawking" },
  { text: "Mathematics is the most beautiful and most powerful creation of the human spirit.", author: "Stefan Banach" },
  { text: "God does not care about our mathematical difficulties. He integrates empirically.", author: "Albert Einstein" },
  { text: "Number is the ruler of forms and ideas.", author: "Pythagoras" },
  { text: "Geometry is knowledge of the eternally existent.", author: "Plato" },
  { text: "If I have seen further it is by standing on the shoulders of Giants.", author: "Isaac Newton" },
  { text: "I can calculate the motion of heavenly bodies, but not the madness of people.", author: "Isaac Newton" },
  { text: "Tact is the knack of making a point without making an enemy.", author: "Isaac Newton" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "The computer was the most remarkable tool we’ve ever come up with.", author: "Steve Jobs" },
  { text: "We are all now connected by the Internet, like neurons in a giant brain.", author: "Stephen Hawking" },
  { text: "The big mobile companies are the ones that are going to win.", author: "Eric Schmidt" },
  { text: "The Internet is the first thing that humanity has built that humanity doesn't understand.", author: "Eric Schmidt" },
  { text: "AI is probably the most important thing humanity has ever worked on.", author: "Sundar Pichai" },
  { text: "The best way to build a brand is to build a great product.", author: "Sundar Pichai" },
  { text: "Be impatient with your actions but patient with your results.", author: "Naval Ravikant" },
  { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { text: "Physics is like sex: sure, it may give some practical results, but that's not why we do it.", author: "Richard Feynman" },
  { text: "Coding is today's language of creativity.", author: "Maria Klawe" }
];
